// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPtb60dthvTPLmaRlL_E7YOsBDIAK-vKw',
    appId: '1:12884863424:web:118596ddc05d1b040fc025',
    messagingSenderId: '12884863424',
    projectId: 'sample-79b30',
    authDomain: 'sample-79b30.firebaseapp.com',
    databaseURL: 'https://sample-79b30-default-rtdb.firebaseio.com',
    storageBucket: 'sample-79b30.firebasestorage.app',
    measurementId: 'G-QTKEV2R8XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Wl7XSKbRAaVCE3ragZbng9xMDKzX45g',
    appId: '1:12884863424:android:12c75f1252667fa80fc025',
    messagingSenderId: '12884863424',
    projectId: 'sample-79b30',
    databaseURL: 'https://sample-79b30-default-rtdb.firebaseio.com',
    storageBucket: 'sample-79b30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAETArZFi3uMzSCdxVmdcfTmQyVEit0qSk',
    appId: '1:12884863424:ios:d064e339852718380fc025',
    messagingSenderId: '12884863424',
    projectId: 'sample-79b30',
    databaseURL: 'https://sample-79b30-default-rtdb.firebaseio.com',
    storageBucket: 'sample-79b30.firebasestorage.app',
    androidClientId: '12884863424-d3c59jb7n94qq418311ij3f4kcntpmdp.apps.googleusercontent.com',
    iosClientId: '12884863424-jatj2nt4jjeq8f1cvi3vabr78krbv1n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bantay72Users',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAETArZFi3uMzSCdxVmdcfTmQyVEit0qSk',
    appId: '1:12884863424:ios:d064e339852718380fc025',
    messagingSenderId: '12884863424',
    projectId: 'sample-79b30',
    databaseURL: 'https://sample-79b30-default-rtdb.firebaseio.com',
    storageBucket: 'sample-79b30.firebasestorage.app',
    androidClientId: '12884863424-d3c59jb7n94qq418311ij3f4kcntpmdp.apps.googleusercontent.com',
    iosClientId: '12884863424-jatj2nt4jjeq8f1cvi3vabr78krbv1n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bantay72Users',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPtb60dthvTPLmaRlL_E7YOsBDIAK-vKw',
    appId: '1:12884863424:web:84011f31bbcb6b470fc025',
    messagingSenderId: '12884863424',
    projectId: 'sample-79b30',
    authDomain: 'sample-79b30.firebaseapp.com',
    databaseURL: 'https://sample-79b30-default-rtdb.firebaseio.com',
    storageBucket: 'sample-79b30.firebasestorage.app',
    measurementId: 'G-6SCCCD97V7',
  );
}
